### ISSUE TITLE
Other PR to consider for fork

### ISSUE THREAD

**Issue by v-kat** [ctron/trunk#1]
I've been having some issues with nix and trunk around runtime dependency fetching.
I believe https://github.com/thedodd/trunk/pull/570 fixes this issue.
If you're going to maintain a fork, I'd be nice to get it included.
I'm likely just going to remove trunk from my project and do everything from scratch otherwise.

**Comment by ctron** [comment]
I pulled in those changes and will release them as `trunk-ng 0.17.6`.

**Comment by ctron** [comment]
https://github.com/ctron/trunk/releases/tag/v0.17.6
