### ISSUE TITLE
No-spa flag

### ISSUE THREAD

**Issue by v-kat** [ctron/trunk#3]
https://github.com/thedodd/trunk/issues/192 was an older trunk issue that's still a problem for some kinds of use of trunk.

I'm currently using a setup where returning a 200 OK for missing assets breaks my code due a 3rd party dependency.

It'd be nice to have something like a `no-spa` flag that would allow this behavior to be changed (e.g. return a 404) and make the usage patterns for this tool more flexible.

**Comment by ctron** [comment]
The idea behind the current implementation is, that a SPA (single page application) can be loaded from any of it paths which might occur only in the history of the browser. And yet, the user might directly navigate to that URL/path, and so the SPA must load. This is done by redirecting the request to the default content.

So a compromise might be to introduce the `--no-spa` flag, and treat all "not found" errors with a 404 instead.
