### ISSUE TITLE
integrity not working

### ISSUE THREAD

**Issue by johan-smits** [ctron/trunk#8]
When I have the `data-integrity="sha384"` option enabled on the module: `<link data-trunk rel="rust" data-integrity="sha384" data-bin="ui" data-cargo-features="ui" data-wasm-opt="z" />` it does not generate the checksum for this module include:

```
  <script type="module">import init from '/ui-327b61ff6dc8826f6d632d0cdc6e0c183dbbb2151d239ca540676b278602adff89f3e975448a0ac90e10369e79d13bf7.js';init('/ui-327b61ff6dc8826f6d632d0cdc6e0c183dbbb2151d239ca540676b278602adff89f3e975448a0ac90e10369e79d13bf7_bg.wasm');</script>
```

With a CSP set it will reject the loading of the init file.

Also the `data-integrity` on css files `<link data-trunk rel="tailwind-css" data-inline="true" data-integrity="sha384" href="/index.css" />` is ignored.

Also the hotload reload script does not calculate a integrity check. Did I overlooked a feature?

**Comment by ctron** [comment]
> Did I overlooked a feature?

Probably not, it need to dig into this. It seems to work fine for the default case (no "rust" link element).

**Comment by ctron** [comment]
I just tried this with the `vanilla` example:

```html
<link data-trunk rel="rust" href="Cargo.toml" data-wasm-opt="z" data-bin="vanilla-example" data-integrity="sha384"/>
```

I get this:

```html
<link rel="preload" href="/vanilla-example-5554b3fb0263ecc163a8c2b0186bdcb31d9fddfa44db6530a6999dce478e1fbd9bd49b619ad1f2810436b68c084cb3b2_bg.wasm" as="fetch" type="application/wasm" crossorigin="anonymous" integrity="sha384-VVSz-wJj7MFjqMKwGGvcsx2f3fpE22UwppmdzkeOH72b1JthmtHygQQ2towITLOy">
<link rel="modulepreload" href="/vanilla-example-5554b3fb0263ecc163a8c2b0186bdcb31d9fddfa44db6530a6999dce478e1fbd9bd49b619ad1f2810436b68c084cb3b2.js" crossorigin="anonymous" integrity="sha384-GhQUkuAgVkhAQOVN0EBEfiqgu4FIIWWolV9m84zBa_dcJ3j2I6KioIs9cxZFTI-s"></head>
<body>
    <script type="module">import init from '/vanilla-example-5554b3fb0263ecc163a8c2b0186bdcb31d9fddfa44db6530a6999dce478e1fbd9bd49b619ad1f2810436b68c084cb3b2.js';init('/vanilla-example-5554b3fb0263ecc163a8c2b0186bdcb31d9fddfa44db6530a6999dce478e1fbd9bd49b619ad1f2810436b68c084cb3b2_bg.wasm');</script>
```

The `<script module>` tag is inline. So a digest doesn't seem to make sense there. But the two included files are covered be the previous link elements.

For CSS and additional JavaScript snippets it's a different story. That's not (yet) covered.

**Comment by johan-smits** [comment]
I get the same, but the issue is when you enable in you CSP the checks, all scripts and stylesheets are ignored if they don't have it set. So also the `type=module` will be rejected because it does not have it.

**Comment by ctron** [comment]
Ok, I see that this will be an issue for the external content. That needs more time, or some helping hands (PRs).

For the `type=module` I would really double check if that's a case (do you have some kind of error report/failure). Because from what I read here, that's only for content which is "fetched":

> Subresource Integrity (SRI) is a security feature that enables browsers to verify that resources they fetch (for example, from a [CDN](https://developer.mozilla.org/en-US/docs/Glossary/CDN)) are delivered without unexpected manipulation. It works by allowing you to provide a cryptographic hash that a fetched resource must match.

— https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

And while it's not explicitly mentioned, the [CSP policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#writing_a_policy) also mentions values for `*-src`, which this tag doesn't have.

I am not saying that is the case, I didn't test. But I think it would be good to test, to be sure.

**Comment by johan-smits** [comment]
Is you have this in a branch I can do a check if this fixes the issues?

**Comment by ctron** [comment]
Yes, it's in the `trunk-ng` branch already.

**Comment by ctron** [comment]
I just pushed another commit, which enables this also for the snippets.

**Comment by ctron** [comment]
This was released with trunk-ng `0.17.14`. Please let me know if there is more to be done.

**Comment by johansmitsnl** [comment]
I have an issue with the integrity checks of the wasm module.

When I run:

`cat dist/kixz-app-ui-695b1ccbfb5a435a94e9e843fc370aef3215852814b2a662fb818c5a281cca99fa6b5577accf25cbc1a00c23154bea0f_bg.wasm | openssl sha384 -binary | openssl base64` => `cmkr0nk99WBmV7l5Skco2msVPCcKUhkjxVv5suJWXKMd8hEhjYtoAd4y8pWaMHer`.

But in the html it says: `aVscy_taQ1qU6ehD_DcK7zIVhSgUsqZi-4GMWigcypn6a1V3rM8ly8GgDCMVS-oP`.

The html include is:

```html
 <link data-trunk rel="rust" data-integrity="sha384" data-bin="kixz-app-ui" />
```

Any idea why these checks are not the same?

**Comment by ctron** [comment]
Depends on which version of trunk you're using. IIRC there was an issue where `wasm-opt` wasn't considered and the digest was generated before running it. That should be solved in all releases of `trunk` (not `trunk-ng`).

**Comment by johansmitsnl** [comment]
Mixed up the repo. Looks like we can switch back again now most features are implemented 👍
