### ISSUE TITLE
__trunk_address__ in WSS url is not getting replaced

### ISSUE THREAD

**Issue by lpotthast** [ctron/trunk#9]
I'm now seeing these browser-console-errors using the latest released trunk-ng build.

`WebSocket connection to 'wss://{{__trunk_address__}}/_trunk/ws' failed: `

Seems that the `html_address_middleware` is not working as it should..

**Comment by ctron** [comment]
That's interesting because (aside from "works for me") the replacement string is lowercase, while it actually is uppercase.

**Comment by ctron** [comment]
So, the only case where this would seem to fail is when the `Host` header is not sent in the request from the browser (or something intercepts this in the middle).
